config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  get '/register', to: 'chefs#new'  # custom route to register new chef
  
  # custom routes for user login/logout
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  has_many :likes
  before_save {self.email = email.downcase}
  validates :chefname, presence: true, length: {minimum: 3, maximum: 40}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
  
  has_secure_password
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef 
  belongs_to :recipe
  
  validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes, dependent: :destroy
  
  validates :chef_id, presence: true
  validates :name, presence: true, length: {minimum: 5, maximum: 100}
  validates :summary, presence: true, length: {minimum: 10, maximum: 150}
  validates :description, presence: true, length: {minimum: 20, maximum: 500}
  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  # order paginated recipes by most recently created
  default_scope -> { order(created_at: :desc) }
  
  # order paginated recipes by most recently updated
  # default_scope -> { order(updated_at: :desc) }
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size
  end
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # make methods available to all views
  helper_method :current_user, :logged_in?

  
  # find which user id is currently in session
  # store current user as variable for all views
  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end
  
  # check if current user is logged in (true or false)
  def logged_in?
    !!current_user
  end
  
  # Only logged in users can perform certain actions, such as creating & editing recipes
  # Users not logged in can only view recipe page and recipes index
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to :back
    end  
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  
  before_action :find_chef, only: [:show, :edit, :update, :destroy] # find chef before showing or editing
  before_action :require_same_user, only: [:edit, :update]          # user can only edit their own profile
  
  # display paginated list of all chefs on chef index
  def index 
    @chefs = Chef.paginate(page: params[:page], per_page: 5)
  end
  
  # register new chef account
  def new
    @chef = Chef.new
  end
  
  def create
    @chef = Chef.new(chef_params)
    
    if @chef.save
      flash[:success] = "Your account has been created successfully."
      session[:chef_id] = @chef.id # start user login session when user creates an account
      redirect_to recipes_path
    else
      render 'new'
    end
  end
  
  # edit chef profile
  def edit 
  end
  
  # if chef profile is updated, save and redirect to chef page
  # otherwise, render edit form again
  def update
    if @chef.update(chef_params)
      flash[:success] = "Your profile has been updated successfully."
      redirect_to chef_path(current_user) # redirect to chef show page
    else
      render 'edit'
    end
  end
  
  # show chef profile
  def show
    @recipes = @chef.recipes.paginate(page: params[:page], per_page: 3) #paginate recipes shown on chef's page
  end
  
  
  private
  
    def chef_params
      params.require(:chef).permit(:chefname, :email, :password)
    end
    
    def find_chef
      @chef = Chef.find(params[:id])
    end
    
    # logged in user can only edit their own profile
    def require_same_user
      if current_user != @chef
        flash[:danger] = "You can only edit your own profile"
        redirect_to :back
      end  
    end
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  # new user log in session
  def new 
  end
  
  # create login session
  def create
    #find user by email
    chef = Chef.find_by(email: params[:email]) 
    
    # authenticate user by password
    # if user is able to log in, redirect to recipes index & store chef_id in browser session
    # otherwise, show error and render log in form again
    if chef && chef.authenticate(params[:password])
      session[:chef_id] = chef.id
      flash[:success] = "You are logged in"
      redirect_to recipes_path
    else
      flash.now[:danger] = "Your email address or password does not match"
      render 'new'
    end
  end
  
  # end user login session
  def destroy
    session[:chef_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  # display main page
  # if user is logged in, display recipes index
  # otherwise, display welcome page
  def home
    redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  before_action :find_recipe, only: [:show, :edit, :update, :like]  # find recipe before showing, editing, or liking
  before_action :require_user, except: [:show, :index]              # users not logged in can only view recipe page and recipes index
  before_action :require_same_user, only: [:edit, :update]          # user can only edit their own recipe
  before_action :admin_user, only: [:destroy]                         # only admin user can delete a recipe
  
  
  def index
    # add pagination and display number of recipe items per page
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end
  
  def show
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_user
    
    if @recipe.save
      flash[:success] = "Your recipe was created successfully!"
      redirect_to recipes_path
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end
  
  def destroy 
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe has been deleted"
    redirect_to recipes_path
  end
  
  def like
    like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was successful"
      redirect_to :back
    else
      flash[:danger] = "You can only like or dislike a recipe once"
      redirect_to :back
    end
  end
  
  private
    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture)
    end
    
    def find_recipe
      @recipe = Recipe.find(params[:id])
    end
  
    # logged in user can only edit their own recipes
    # admin user can edit all recipes
    def require_same_user
      if current_user != @recipe.chef and !current_user.admin?
        flash[:danger] = "You can only edit your own recipes"
        redirect_to :back
      end  
    end
    
    def admin_user
      redirect_to recipes_path unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(chef, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end
  
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2 form-chef">
    <%= form_for @chef do |f| %>
      <%= f.label :chefname %>
      <%= f.text_field :chefname %>
      
      <%= f.label :email %>
      <%= f.email_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.submit(@chef.new_record? ? 'Register' : 'Edit profile', class: "btn btn-success") %>
    <% end %>  
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/page_title', title: "Edit your profile" %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/page_title', title: "All Chefs" %>

<!--nav tabs linking to recipes index and chefs index-->
<ul class="nav nav-tabs">
  <li>
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li class="active">
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<!--Display chefs on page and link to their chef pages-->
<div class="row center">
  <div class="container">
    <% @chefs.each do |chef| %>
      <div class="col-md-4">
        <%= link_to gravatar_for(chef, size: 200), chef_path(chef) %>
        <h5>Chef: <%= chef.chefname %> </h5>
      </div>
    <% end %>
  </div> <!-- .container -->
</div> <!-- .row -->

<!--paginate chefs listing-->
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= will_paginate %>
  </div>
</div>

app/views/chefs/new.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/page_title', title: "Register your account" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/page_title', title: "Chef: " + @chef.chefname %>

<!--Display chef name and gravtar image-->
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @chef, size: 200 %>
    <hr>
  </div>
</div>  

<!--heading & pagination before displaying recipes-->
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <h3>Recipes</h3>
    <!--<%= will_paginate @recipes %>-->
  </div>
</div>

<!--Display recipes created by chef-->
<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p> 
        <%= recipe.summary %>
      </p>
      <p>
        <!--show when recipe was created-->
        <span class="quiet"><small><%= time_ago_in_words(recipe.created_at) %> ago</small></span>
        <!--show when recipe was updated-->
        <!--<span class="quiet"><small> updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span> -->
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= recipe.thumbs_up_total %>
        <% end %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div> <!-- .row -->
<% end %>


<!--paginate list of recipes-->
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= will_paginate @recipes %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer to be used on all pages -->
<footer>
  <p>&copy; RecipeBox 2016</p>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<!-- Header to be used on all pages -->
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Recipe Box", root_path, class: "", id: "logo" %>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!--if a user is logged in... -->
        <% if logged_in? %>
          <!--show link to logout-->
          <div class="nav-item navbar-right">
            <%= link_to "Logout", logout_path, class: "btn btn-sm btn-danger" %>
          </div>
          
          <!-- show link to edit profile-->
          <div class="nav-item navbar-right">
            <%= link_to "Edit Profile", edit_chef_path(current_user), class: "btn btn-sm btn-info" %>
          </div>
          
          <!--show link to view profile-->
          <div class="nav-item navbar-right">
            <%= link_to "View Profile", chef_path(current_user), class: "btn btn-sm btn-info" %>
          </div>
        
          <!--show link to create new recipe -->
          <div class="nav-item navbar-right">
            <%= link_to "New Recipe", new_recipe_path, class: "btn btn-sm btn-info" %>
          </div>
          
        <% else %>
          <!--otherwise, if user is not logged in, show link to log in-->
          <div class="nav-item navbar-right">
            <%= link_to "Login", login_path, class: "btn btn-sm btn-info" %>
          </div>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  
  </div> <!-- .container -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Recipe Boxx</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= @body_id if @body_id %>">

  <!-- Page Content -->
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/page_title', title: "Log In" %>

<div class="row">
  <div class="col-md-6 col-md-offset-3 well form-register">
    
    <%= form_tag '/login' do %>
      <%= label_tag :email %>
      <%= email_field_tag :email %>  <!-- instead of text_field_tag ? --> 
      
      <%= label_tag :password %>
      <%= password_field_tag :password %>
      
      <%= submit_tag 'Login', class: "btn btn-success" %>
      
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<% @body_id = "homepage" %>
<%= render 'shared/nav_transparent' %>

<div class="jumbotron center">
  <h1>Welcome to Recipe Box</h1>
  
  <!--<h2>This is the home page.</h2>-->
  
  <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>
  
  <div class="row home-section-2">
    <div class="col-md-4">
      <h3 class="midrow">View Recipes as Guest User</h3>
      <h2 class="midrow-subtitle">Browse &amp; view recipes as a guest</h2>
      <!--<h2 class="left">Browse and view recipes as a guest and sign up later</h2>-->
      <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-small btn-warning" %></p>
    </div>
    
    <div class="col-md-4">
      <h3 class="midrow">Sign in to your account</h3>
      <h2 class="midrow-subtitle">Manage your recipes</h2>
      <!--<h2 class="left">Manage your recipes <br> Add, edit & review</h2>-->
      <p><%= link_to "Log in to your account", login_path, class: "btn btn-small btn-warning" %></p>
    </div>
    
    <div class="col-md-4">
      <h3 class="midrow">View Chefs as a Guest User</h3>
      <h2 class="midrow-subtitle">Browse &amp; view chefs as a guest</h2>
      <!--<h2 class="left">Browse and view recipes as a guest and Sign Up later</h2>-->
      <p><%= link_to "View Chefs Listing", chefs_path, class: "btn btn-small btn-warning" %></p>
    </div>
  </div>

</div>

<!--<div class="row">-->
<!--  <div class="col-md-4">-->
<!--    <h3 class="midrow">View Recipes as Guest User</h3>-->
<!--    <h2 class="left">Browse and view recipes as a guest and Sign Up later</h2>-->
<!--    <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-small btn-warning" %></p>-->
<!--  </div>-->
  
<!--  <div class="col-md-4">-->
<!--    <h3 class="midrow">View Recipes as Guest User</h3>-->
<!--    <h2 class="left">Browse and view recipes as a guest and Sign Up later</h2>-->
<!--    <p><%= link_to "Browse Recipe Listings", "", class: "btn btn-small btn-warning" %></p>-->
<!--  </div>-->
  
<!--  <div class="col-md-4">-->
<!--    <h3 class="midrow">View Recipes as Guest User</h3>-->
<!--    <h2 class="left">Browse and view recipes as a guest and Sign Up later</h2>-->
<!--    <p><%= link_to "Browse Recipe Listings", "", class: "btn btn-small btn-warning" %></p>-->
<!--  </div>-->
<!--</div>-->

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2 form-recipe">
    <%= form_for(@recipe, html: { multipart: true }) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>
      
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
      </span>
      
      <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success") %>
    <% end %>  
  </div>
</div>

<script>
  $('#recipe_picture').bind('change'), function(){
      size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes) > 5 {
        alert('Maximum file size is 5MB. Please choose a smaller file.');
      }
  });    
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/page_title', title: "Edit Recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/page_title', title: "All Recipes" %>

<!--nav tabs linking to recipes index and chefs index-->
<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= link_to gravatar_for(recipe.chef, size: 120), chef_path(recipe.chef) %>
        <h5>Chef name: <%= recipe.chef.chefname %></h5>
      </section>
    </div>
    
    <!--<div class="col-lg-6 well">-->
    <div class="col-lg-7 well">  
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p>
        <!--show when recipe was created-->
        <span class="quiet"><small><%= time_ago_in_words(recipe.created_at) %> ago</small></span> 
        <!--show when recipe was updated-->
        <!--<span class="quiet"><small> updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span> -->
      </p> 
      <div class="pull-right">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= recipe.thumbs_up_total %>
          <% end %>
          &nbsp;&nbsp;&nbsp;
          <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= recipe.thumbs_down_total %>
          <% end %>
        </div>
    </div>
    
    <!--<div class="col-md-4">-->
    <div class="col-md-2 index-recipe-img">
      <%= image_tag(recipe.picture.url, size: "250x158", class: "gravatar") if recipe.picture? %>
    </div>
  </div>
<% end %>

<div class="col-md-6 col-md-offset-3 center">
    <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/page_title', title: "Create A New Recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/page_title', title: @recipe.name %>

<div class="row center recipe-show-summary">
  <h3><%= @recipe.summary %></h3>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="center">
      <%= image_tag(@recipe.picture.url, class: "gravatar show-recipe-img") if @recipe.picture? %>
    </div>
    
    <div class="col-md-10 col-md-offset-1 well recipe-show-description">
      <p>
        <%= simple_format(@recipe.description) %>
        
        <div class="pull-right">
          <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= @recipe.thumbs_up_total %>
          <% end %>
          &nbsp;&nbsp;&nbsp;
          <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= @recipe.thumbs_down_total %>
          <% end %>
        </div>
      </p>
    </div>
  </div>
  
  <div class="col-md-3 center">
    <%= link_to gravatar_for(@recipe.chef, size: 200), chef_path(@recipe.chef) %>
    
    <h5>Brought to you by: <%= @recipe.chef.chefname %></h5>
    
    <div class="recipe-show-btns">
      <h5><%= link_to "View All Recipes", recipes_path, class: "btn btn-warning btn-small"  %></h5>
    
      <!-- limit ability to edit recipe to the chef who created it, or admin user-->
      <div class="recipe-show-btn-edit">
        <% if logged_in? and (@recipe.chef == current_user || current_user.admin?) %>
          <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class:"btn btn-success" %>
        <% end %>
      </div>
      
      <!-- limit ability to delete recipe to admin user -->
      <div class="recipe-show-btn-delete">
        <% if logged_in? and current_user.admin? %>
          <%= link_to "Delete this recipe", @recipe, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger" %>
        <% end %>
      </div>
      
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<!-- Header to be used on all pages except homepage -->
<header class="navbar navbar-fixed-top navbar-default navbar-solid">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Recipe Box", root_path, class: "", id: "logo" %>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!--if a user is logged in... -->
        <% if logged_in? %>
          <!--show link to logout-->
          <div class="nav-item navbar-right">
            <%= link_to "Logout", logout_path, class: "btn btn-sm btn-danger" %>
          </div>
          
          <!-- show link to edit profile-->
          <div class="nav-item navbar-right">
            <%= link_to "Edit Profile", edit_chef_path(current_user), class: "btn btn-sm btn-info" %>
          </div>
          
          <!--show link to view profile-->
          <div class="nav-item navbar-right">
            <%= link_to "View Profile", chef_path(current_user), class: "btn btn-sm btn-info" %>
          </div>
        
          <!--show link to create new recipe -->
          <div class="nav-item navbar-right">
            <%= link_to "New Recipe", new_recipe_path, class: "btn btn-sm btn-info" %>
          </div>
          
        <% else %>
          <!--otherwise, if user is not logged in, show link to log in-->
          <div class="nav-item navbar-right">
            <%= link_to "Login", login_path, class: "btn btn-sm btn-info" %>
          </div>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  
  </div> <!-- .container -->
</header>

app/views/shared/_nav_transparent.html.erb
<!-- Header to be used on home page -->
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Recipe Box", root_path, class: "", id: "logo" %>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!--if a user is logged in... -->
        <% if logged_in? %>
          <!--show link to logout-->
          <div class="nav-item navbar-right">
            <%= link_to "Logout", logout_path, class: "btn btn-sm btn-danger" %>
          </div>
          
          <!-- show link to edit profile-->
          <div class="nav-item navbar-right">
            <%= link_to "Edit Profile", edit_chef_path(current_user), class: "btn btn-sm btn-info" %>
          </div>
          
          <!--show link to view profile-->
          <div class="nav-item navbar-right">
            <%= link_to "View Profile", chef_path(current_user), class: "btn btn-sm btn-info" %>
          </div>
        
          <!--show link to create new recipe -->
          <div class="nav-item navbar-right">
            <%= link_to "New Recipe", new_recipe_path, class: "btn btn-sm btn-info" %>
          </div>
          
        <% else %>
          <!--otherwise, if user is not logged in, show link to log in-->
          <div class="nav-item navbar-right">
            <%= link_to "Login", login_path, class: "btn btn-sm btn-info" %>
          </div>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  
  </div> <!-- .container -->
</header>

app/views/shared/_page_title.html.erb
<p>
  <h1> <%= title %> </h1>
  <hr>
</p>